

tasks:
#  - name: backend
#    before: |
#      sdk install java 17.0.4.1-tem < /dev/null
#    init: |
#      ./mvnw spring-boot:run
#    command: |
#      echo Backend running

  - name: frontend
    before: |
      cd ./react-app
    init: |
      npm install
    command: |
      npm start
      echo Frontend running

ports:
  - name: AfP Sample App
    description: Frontend
    port: 3000
    visibility: public
    onOpen: open-browser

vscode:
  extensions:
    - pivotal.vscode-spring-boot
    - vscjava.vscode-java-pack
