

tasks:
  - name: backend
    before: |
      sdk install java 17.0.4.1-tem < /dev/null
    init: |
      ./mvnw spring-boot:run
    command: |
      echo Backend running

  - name: frontend
    before: |
      cd ./react-app
    init: |
      echo npm install
      echo npm start
    command: |
      echo Frontend running
      
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - pivotal.vscode-spring-boot
    - vscjava.vscode-java-pack
